# Generated by Django 5.2.8 on 2025-12-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='URL用文字列'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='category',
            field=models.CharField(choices=[('work', '仕事'), ('personal', '個人'), ('study', '勉強'), ('hobby', '趣味'), ('other', 'その他')], default='personal', max_length=20, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='priority',
            field=models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高')], default=2, verbose_name='重要度'),
        ),
    ]
