# Generated by Django 5.2.8 on 2026-01-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_memo_slug_alter_memo_category_alter_memo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
